"""
AI Shayak — Core ethics, fairness, security, and compliance audit logic.
Facade module maintaining full backwards compatibility.
"""

from __future__ import annotations

from core import (
    ALLOWED_MODEL_EXTS,
    MAX_DATASET_BYTES,
    MAX_MODEL_BYTES,
    _load_model_and_data,
    adversarial_robustness,
    audit_privacy,
    audit_robustness,
    build_report_text,
    calculate_fairness_metrics,
    calculate_regression_fairness,
    calibration_parity,
    detect_model_framework,
    differential_privacy_audit,
    extract_target,
    generate_compliance_report,
    generate_mitigation_plan,
    generate_retraining_suggestions,
    intersectional_analysis,
    is_numeric_dtype,
    load_model,
    logger,
    membership_inference_attack,
    predict_model,
    predict_proba_model,
    preview_dataset,
    run_deep_audit,
    run_evaluate,
    run_optimize,
    run_security_audit,
    safe_run,
    temp_upload,
    tune_thresholds,
    validate_model_filename,
    validate_sensitive_column,
)

__all__ = [
    "MAX_MODEL_BYTES",
    "MAX_DATASET_BYTES",
    "ALLOWED_MODEL_EXTS",
    "is_numeric_dtype",
    "detect_model_framework",
    "predict_model",
    "predict_proba_model",
    "load_model",
    "calculate_fairness_metrics",
    "calculate_regression_fairness",
    "intersectional_analysis",
    "calibration_parity",
    "tune_thresholds",
    "generate_retraining_suggestions",
    "adversarial_robustness",
    "differential_privacy_audit",
    "membership_inference_attack",
    "audit_robustness",
    "audit_privacy",
    "generate_mitigation_plan",
    "generate_compliance_report",
    "extract_target",
    "temp_upload",
    "validate_sensitive_column",
    "validate_model_filename",
    "preview_dataset",
    "run_evaluate",
    "_load_model_and_data",
    "run_deep_audit",
    "run_optimize",
    "run_security_audit",
    "build_report_text",
    "safe_run",
]
